### PR TITLE
Analyze catecoord

### PR DESCRIPTION
**Pull request by bcipolli**
This is a continuation of https://github.com/bcipolli/DifferentialEncoding/pull/7 with @vishaalprasad

### CODE REVIEW

**Comment by bcipolli** [comment]
@vishaalprasad Can you set up your git config so that your commits belong to your account please?
see: https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup#Your-Identity

**Comment by bcipolli** [comment]
@vishaalprasad pinged you on 3 commits. In addition, the code isn't working when I run 50 model runs. The error seems to indicate that something is off: I have 46 models for left hemisphere, and *56* for right hemisphere. This is impossible--max # of models is 50.

image

So, I believe there's an error in `de_StaticizerCC`. Not sure what it is, but if you could take a look that'd be great!

**Comment by vishaalprasad** [comment]
Should I follow these
<https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/>
instructions
to get a local working copy of all your changes?

**Comment by bcipolli** [comment]
Kinda. I mentioned earlier how to add a remote. While on your local branch, you just pull from the remote:
`git pull upstream master`
where upstream corresponds the `guruucsd` remote repository, which was added when you ran:
`git remote add -f upstream git@github.com:guruucsd/DifferentialEncoding  # might require https syntax..`

**Comment by vishaalprasad** [comment]
Hmm I did that, but a lot of my conflicts are strange here. It doesn't look
like the guruucsd repository is fully updated?

Here's a conflict I get in uber_slotnick_all.m...?

<<<<<<< HEAD
[args,opts] = uber_slotnick_args( 'plots', plots, 'stats', stats, 'runs',
5, 'ac.AvgError', 2E-4);
=======
[args,opts] = uber_kitterle_args( 'plots', plots, 'stats', stats);
>>>>>>> ced2d0ebfaf6ae087f63fb137bee3b8a1e02d6d1

I don't understand why it would want to change back to kitterle...?

**Comment by bcipolli** [comment]
Sorry, you're right--we didn't merge it there yet. I forgot that we merged
it to my branch instead.

So you have to abort that (`git reset --hard HEAD` will revert everything
to your last commit), and you should pull from my branch:
`git pull bcipolli analyze-catecoord` (or whatever it's called)

**Comment by bcipolli** [comment]
@vishaalprasad The # of models needs to be matched across hemispheres to do the group anova. Please look into taking care of that, while I figure out why we got so many rejections.

**Comment by vishaalprasad** [comment]
@bcipolli, OK. Question: Should "nInst" be one for our experiment? (nInst
= min([nInstCate nInstCoord]);)

**Comment by vishaalprasad** [comment]
@bcipolli, I believe "

    idxCoor_old = mod(coord.anova.(ds).S_n-1, max(nInstCoord))+1;

    idxCoor_cur = (idxCoor_old <= nInst);  "

is the problem. Assume size(idxCate*) = 46, and size(idxCoor_old) = 58. If
so, the second line doesn't do anything; I *think *it's supposed to update
idxCoor_cur to be the first 46 (i.e. min(accepted trials of Cate, Coor))
 values of idxCoor_old (correct me if I'm wrong)? But nInst = 1, and
idxCoor_old is just an array of 1s, so all of idxCoor_old is retained
following the second statement. I think that's what's going on, anyways.
The code is kind of obtuse.


Another thing: 15 trials gives me Y's of size 58 & 46. Those are strange
values considering 50 trials gives Y's of size 56 & 46.

**Comment by bcipolli** [comment]
@vishaalprasad Please take a look at the markdown styling. Code can be quoted using single backtick inline (i.e. `code`), or triple ``` in a block, as in:
```matlab
    idxCoor_old = mod(coord.anova.(ds).S_n-1, max(nInstCoord))+1;
    idxCoor_cur = (idxCoor_old <= nInst); 
```
and text can be quoted using greater than:
> what you said

So,
>Another thing: 15 trials gives me Y's of size 58 & 46. Those are strange
values considering 50 trials gives Y's of size 56 & 46.

Yep. Please debug and find out what's going on there.

I didn't understand the rest of what you were saying. Best to mention what the inputs are to the code that you don't understand, what output you see out of the code, and how you think the code is getting there. Use the markdown to make it readable, and I'll take another look. Thanks!

**Comment by vishaalprasad** [comment]
code: 'idxCate_cur = (idxCate_old <= nInst); 
idxCoor_old = mod(coord.anova.(ds).S_n-1, max(nInstCoord))+1;
idxCoor_cur = (idxCoor_old <= nInst); '

Background: idxCate_old = idxCate_cur = 46. idxCoor_old=idxCoor_new = 58.

Question: What is nInst? What is this code trying to do? The second line doesn't do anything at all as currently written, i.e. idxCoor_new = idxCoor_old, idxCate_bew = idxCate_old no matter what values are there. What *should* the values be in the example above?

I can't debug this until I know what the code is trying to do, and it's too obtuse with too sparse commenting for me to deduce it.

**Comment by bcipolli** [comment]
OK, I can take a look. Can you provide me with a link to the file and line you're referring to?

**Comment by vishaalprasad** [comment]
Lines 18-26, de_StatsGroupBasicsSlot.m

**Comment by bcipolli** [comment]
Thanks. The link is https://github.com/vishaalprasad/DifferentialEncoding/blob/analyze-catecoord/code/_expts/slotnick_etal_2001/analyze/stats/de_StatsGroupBasicsSlot.m#L18

If you can include those, it makes things much easier. It's also generally expected in open-source code communities during discussions.

I'll take a look!

**Comment by vishaalprasad** [comment]
Oops, my bad! Will do so next time.

**Comment by bcipolli** [comment]
```
    idxCat_old = mod(cate.anova.(ds).S_n-1, max(nInstCate))+1;
    idxCat_cur = (idxCat_old <= nInst);
```
Model instances are enumerated in `cate.anova.(ds).S_n`. This code is trying to extract the indices of model instances used in this analysis.

I'm not sure why the `mod` is needed. I'd have to debug to figure out why... but regardless, that's the semantic of the code. Does that help?

**Comment by vishaalprasad** [comment]
> extract the indices of model instances used in this analysis.

I'm not sure what this means. As far as I can tell, these indices are just a long vector of 1s? And how about

         idxCat_cur = (idxCat_old <= nInst);

? What is this supposed to do?

**Comment by bcipolli** [comment]
`     idxCat_cur = (idxCat_old <= nInst);`

I believe `idxCat_old` should be some number representing the model instance (1 to 50, say). This just returns a binary index indicating whether the model instance should be included (all models instances enumerated <= nInst are included).

I remember reading together that `S_n` was the instance number. I don't think it's 0 or 1. Did you debug and see that it is?

**Comment by vishaalprasad** [comment]
No, it's not 0s and 1s. But because `nInstCate = 1`,

        idxCat_old = mod(cate.anova.(ds).S_n-1, max(nInstCate))+1;

means that the idxCat_old becomes just a vector of all 1s.

> all models instances enumerated <= nInst are included

nInst = 1, so that doesn't really make sense. That would imply no model instance is included.

**Comment by bcipolli** [comment]
OK. `nInstCate` surely should not be 1; it's supposed to be the # of good model instances from the `categorical` task. So it looks like it's an issue of data not being of shape `nModels`x`nTrials`...
```
  nInstCate = [ size(cate.perf.(ds){1},1), ...
        size(cate.perf.(ds){end},1) ];
```

**Comment by vishaalprasad** [comment]
Ah. 

   K>> cate.perf.(ds){1}

     ans = 

    [14x15 double]    [14x5 double]

This is to separate out the two trial types. I'm fairly sure this is intentional. Should I make a change in staticizer or just make the appropriate fix in the GroupsBasic file?

One other thing: Here is the print out of  `cate.anova.(ds).S_n-1` :  

    9
    15
    16
    17
    18
    19
    20
    21
    22
    10
    11
    12
    13
    14
     0
     1
     2
     3
     4
     5
     6
     7
     8
     9
    15
    16
    17
    18
    19
    20
    21
    22
    10
    11
    12
    13
    14
     0
     1
     2
     3
     4
     5
     6
     7
     8

Based on this output, what should `nInstCate` be?

**Comment by bcipolli** [comment]
Right. `nInstCate` should be 14. Now I remember why the `mod` is there; `S_n` for LH is `1:14`, and RH is `15:28`. Can you add a comment in there about that?

**Comment by vishaalprasad** [comment]
How did you get 14? There are 23 good trials of Categorical here (with 2 values, one for each trial type, hence an array size of 46 data points). As opposed to Coordinate, which has 29 good trials (58 trials).

So shouldn't nInstCate be 23?

Or am I misunderstanding?

**Comment by bcipolli** [comment]
I got it from here:
```
K>> cate.perf.(ds){1}

 ans = 

[14x15 double]    [14x5 double]
```
The first dimension is 14, indicating 14 good model instances for the `categorical` task. Where are you getting 23 from? And what do you mean by a "trial"? When I say data are shape `nModels`x`nTrials`, I mean a trial is a model's response to a particular stimulus, and `nModels` is # of model instances.

**Comment by vishaalprasad** [comment]
Oh, that's because:

    
K>> cate.perf.(ds){2}

    ans = 

        [9x15 double]    [9x5 double]

And as you can see from the print out above, `cate.anova.(ds).S_n-1` ranges from 0-22.

**Comment by bcipolli** [comment]
I believe this means 14 LH models, 9 RH models. So `nInstCate` should be `[14 9]`.

**Comment by vishaalprasad** [comment]
Hm. Are you free to meet tomorrow? I think it'll be easier if we just talk about this in person.

**Comment by bcipolli** [comment]
Sure, I'll be around. We can also migrate to gitter, to text-chat as well.

**Comment by vishaalprasad** [comment]
Alright. I think it'll be a little bit easier to just talk in person, so I'll see you tomorrow.

**Comment by bcipolli** [comment]
Closing in favor of #28

**Pull request closed without merging**
