### PR TITLE
Freqpref analysis

### PR DESCRIPTION
**Pull request by bcipolli**
Adds code to analyze the distribution of frequency preferences over hidden units.

### CODE REVIEW

**Comment by bcipolli** [comment]
uber_sergent_sergent u0 p0 _65276599-std-freq-pref-distns-r50-250--small

This is how things looked before refactoring. Things look vastly different after refactoring, and I can't figure out why. I assume the first is correct, because the FFTs indicate a RH / low frequency , LH / high frequency preference.

uber_sergent_sergent u0 p0 _60827550-freq-std-pref-distns-r5-250--medium

**Comment by bcipolli** [comment]
Needs more work... results are a bit odd.

**Comment by bcipolli** [comment]
@vishaalprasad This could be relevant to what we're doing now. It uses the technique in the `scripts/recfields` directory for analyzing frequency preferences, but applies it to autoencoders trained on natural images.

`vary_sigma` here also seems to be working well. The output with the graded red lines is the most relevant one.

Let me know what I could do to hand this off to you properly. Perhaps a Skype meeting could help?

image

**Comment by vishaalprasad** [comment]
Thanks for all of this stuff! I definitely think a Skype meeting would be great so that I can take over. Let me know when you're free! In the mean time, I should probably wrap up all of the code I've written since my last PR and make another PR, so be on the lookout for that!

**Comment by bcipolli** [comment]
Sounds great :) I will let you know a time to Skype, my night schedule is looking a bit crazy these days :) Maybe tomorrow afternoon!

**Comment by vishaalprasad** [comment]
Sure thing! I have class Tu/Th from 11-3 but aside from those times I should be free.

**Pull request merged**
