### PR TITLE
Analyze catecoord

### PR DESCRIPTION
**Pull request by vishaalprasad**
Create a subplot with the same y-limits that allows for a visual comparison between different sigma levels.

(Note: It just occurred to me it would be useful in the plot to know which sigma corresponds to which image in the subplot. Will fix next time.)

### CODE REVIEW

**Comment by bcipolli** [comment]
I will pull this code and try it out, thanks!

**Comment by bcipolli** [comment]
Two issues I see:
1. It is saying `n=2` instead of `n=50`. Is that something you could find & fix?
2. I don't see where the combined plot is saved; could you point me to that?

![Uploading uber_slotnick_all[u0,p0]_89888855-blobdot_coordinate-r50-blob-dot-coordinate-medium-img2pol-location-LVF.png…]()
uber_slotnick_all u0 p0 _90272501-blobdot_categorical-r50-blob-dot-categorical-medium-img2pol-location-lvf

**Comment by vishaalprasad** [comment]
#1: Fixed!
#2: I'm not quite sure how to do it within the framework. Will a call to
de_SaveFig suffice?

**Comment by bcipolli** [comment]
Best thing is to refer to previous code. That's what I just did:
https://github.com/guruucsd/DifferentialEncoding/blob/c527a9cb7944124f541447e37280cd0cc00ceb55/code/_expts/kitterle_etal_1992/analyze/plots/de_PlotsGroupBasicsKit.m#L38

There's probably a better way. I searched for `de_SaveAll`
https://github.com/guruucsd/DifferentialEncoding/blob/c527a9cb7944124f541447e37280cd0cc00ceb55/code/io/de_SaveAll.m

And there's a `de_Save_Plots` that you can try to use, if you are so inclined. If you do, I suggest modifying the kitterle code as well.
https://github.com/guruucsd/DifferentialEncoding/blob/c527a9cb7944124f541447e37280cd0cc00ceb55/code/io/de_SaveAll.m#L36

**Comment by vishaalprasad** [comment]
The latter two both pass in mSets, which I don't have anymore I think. I'll
copy how you did it in the Kitterle code. Do I need a call to de_NewFigs
(or indeed any de function) at all? Since it seems you just save the plot
using print.

Also, I don't see how the Kitterle code works with the right path names.
Doesn't this code save to the directory that the PlotGroupBasicsKit file is
in?

**Comment by bcipolli** [comment]
>Also, I don't see how the Kitterle code works with the right path names. Doesn't this code save to the directory that the PlotGroupBasicsKit file is in?

Yep, it does--good call! I was too lazy to care at that point. 

You could call `de_SavePlots` from inside the top-level script. you have `mSets` there.

**Comment by vishaalprasad** [comment]
Cool! I think I got it to work. Should save where you expect it to! Going
to go through your comments and make sure everything is fixed and then push!

**Comment by bcipolli** [comment]
Great, looks like it was pushed; I'll pull it and try it!

**Comment by bcipolli** [comment]
uber_slotnick_all u0 p0 _90272501-blobdot_comparison-r50-blob-dot-categorical-medium-img2pol-location-lvf

Looks great.. and interesting!

**Comment by bcipolli** [comment]
Actually, the group plot has an issue: please see https://github.com/guruucsd/DifferentialEncoding/issues/29 . Merging this as-is; lots of good stuff to work off of!

**Pull request merged**
