### PR TITLE
Push frequency preferences code into autoenconder visualization.

### PR DESCRIPTION
**Pull request by bcipolli**
In addition to the above change, I found a bug in how random seeds were being set. By fixing this, changing the order of sigmas, or removing a sigma from the set will still allow other models to hit the model cache. Before, the random seed was highly dependent on the position in the list of sigmas / other model parameters, which is bad.

This may cause previous cached model results to be cache-missed. Too bad, so sad!

Will post some results from the viz here, when I get the latest!

### CODE REVIEW

**Comment by bcipolli** [comment]
With `nConns = 10`, `hpl = 4`, `image size 34x25`, I got this:

I had tried `nConns = 5` and `hpl = 4`, and had gotten slightly nicer results - but not like what we'd seen elsewhere. Wondering .. what the original experiments were trained on? Or was that random connectivity / weights?

vanhateren u0 p0 _52622285-output std vs frequency per sigma-r10-250--small
vanhateren u0 p0 _52622285-sigma vs crossover-r10-250--small

**Comment by vishaalprasad** [comment]
If I'm understanding your question correctly, you're wondering why that
curve isn't as nice as the crossover plots that I have on the Differential
Encoding Results doc? That was trained on spatial frequency gratings. Does
that answer your question?

**Comment by bcipolli** [comment]
@vishaalprasad perfect. I'll set that up in the core code, and see if I can replicate those results!

**Comment by vishaalprasad** [comment]
It should already be set up in recfields/sigma_vs_crossover, so take a look at that.

**Comment by bcipolli** [comment]
Soooo.. turns out that @vishaalprasad already did this work, and that it was working well. this PR is really simply code cleanup and bugfixes.

image

image

**Comment by vishaalprasad** [comment]
Looks good to me

**Pull request merged**
